### ISSUE TITLE
implement canEnter() method in Tile class

### ISSUE THREAD

**Issue by petterdaae** [inf112-v19/Bender#51]
Would be nice to know if a robot can enter a tile from some direction. Could we have a method `boolean canEnter(Direction direction)` that checks walls and stuff?

**Comment by AndreasCanAtakan** [comment]
canMove() will create a chain of conditions with the result of its canMove() call and the canMove() call of its neighbor. This will be done recursively with successive neighbors until a result is found.

moveRobot() will follow a similar structure with successive moveRobot() method calls

**Comment by petterdaae** [comment]
@AndreasCanAtakan  I don't think that it is necessary that canMove() is recursive. Should'nt it just check wall stuff?

**Comment by AndreasCanAtakan** [comment]
@petterdaae I'm not quite sure yet, but I think it will have to be recursive because of the fact that the canMove() method has to confirm that the move is valid for neighbors as well. For example, the case where a robot will push another robot during the move, the canMove() method has to check if the move is valid for the neighboring robot as well.
What do you think?

**Comment by petterdaae** [comment]
Oh, sry, my bad. I was thinking about canEnter()
